
group: edge

services:
  - docker

env:
  global:
    - CONSUL_VERSION=${CONSUL_VERSION:-1.3.1}
    - BUILD_DATE=$(date +"%Y-%m-%d")

jobs:
  include:
    - stage: build docker image
      script:
        - make

    - stage: test images
      script:
        - make
        - make compose-file
        - docker-compose up --build -d
        - make test
        - docker-compose kill
        - docker-compose down

    - stage: push latest docker image
      script:
        - make
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker tag  ${USER}/consul:latest ${DOCKER_USERNAME}/docker-consul:latest
        - docker push ${DOCKER_USERNAME}/docker-consul:latest
        - docker logout

    - stage: push version docker image
      if: branch = master
      script:
        - make
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - docker tag  ${USER}/consul:latest ${DOCKER_USERNAME}/docker-consul:${CONSUL_VERSION}
        - docker push ${DOCKER_USERNAME}/docker-consul:${CONSUL_VERSION}
        - docker logout
