---
version: '3.3'

networks:
  frontend:
  backend:

services:
  nginx:
    restart: always
    image: bodsch/docker-nginx
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
    depends_on:
      - consul-master
    links:
      - consul-master:consul
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
      - backend

  consul-master:
    build: .
    container_name: consul-master
    hostname: consul-master
    ports:
      - 8400
      - 8500
    command: 'agent -data-dir /data -server -bootstrap-expect 3 -ui -client=0.0.0.0'
    # -config-file=/etc/consul.d/server.json'
    networks:
      - backend

  consul2:
    build: .
    container_name: consul2
    hostname: consul2
    ports:
      - 8400
      - 8500
      - 8600
    links:
      - consul-master:consul-master
    command: 'agent -data-dir /data -server -join consul-master'
    networks:
      - backend

  consul3:
    build: .
    container_name: consul3
    hostname: consul3
    ports:
      - 8400
      - 8500
      - 8600
    links:
      - consul-master:consul-master
    command: 'agent -data-dir /data -server -join consul-master'
    networks:
      - backend
