---
version: '3.3'

services:
  nginx:
    restart: always
    image: bodsch/docker-nginx
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
    depends_on:
      - consul-master
    links:
      - consul-master:consul
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
      - backend
