#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

[[ -e hooks/environment ]] && . hooks/environment

cat << EOF > .env
BUILD_IMAGE=${BUILD_IMAGE}
BUILD_DATE=${BUILD_DATE}
BUILD_VERSION=${BUILD_VERSION}
VAULT_VERSION=${VAULT_VERSION}

EOF

docker-compose \
  --file compose/head.yml \
  --file compose/nginx.yml \
  --file compose/consul-master.yml \
  --file compose/consul2.yml \
  --file compose/consul3.yml \
  config > docker-compose.yml
